### ISSUE TITLE
How to do this situation?

### ISSUE THREAD

**Issue by sy-project** [MentorEmbedded/mpsoc-manifest#14]
![asfa41dg56](https://user-images.githubusercontent.com/42532250/76697498-59484180-66db-11ea-8eda-df2eed31d6e2.PNG)

i want set android on zcu104
i command "sudo device/xilinx/common/scripts/mksdcard.sh /dev/mmcblk0 zcu106 es2" of Preparing SD Card.
but result is this photo...

how to solve this problem?

![das415fs](https://user-images.githubusercontent.com/42532250/76697568-2c485e80-66dc-11ea-8838-34af81b4a4e3.PNG)

sdcard : Sandisk 16GB

**Comment by sy-project** [comment]
![1561321](https://user-images.githubusercontent.com/42532250/76698392-a8936f80-66e5-11ea-9906-6042ba3f3577.PNG)

**Comment by afirago** [comment]
zcu104 is not supported
